#!/usr/bin/env bash

. "${SHMATE_LIB_DIR}/job.sh"

_test_attached_job() {
    test -z "${_SHMATE_GUARDIAN_PID}"
    shmate_assert "_SHMATE_GUARDIAN_PID must be empty, but is \"${_SHMATE_GUARDIAN_PID}\"" || return $?

    test -n "${_SHMATE_PID_FILE}"
    shmate_assert "_SHMATE_PID_FILE must not be empty" || return $?

    test -n "${_SHMATE_JOB_NAME}"
    shmate_assert "_SHMATE_JOB_NAME must not be empty" || return $?

    test -z "${_SHMATE_JOB_RUN_DIR}"
    shmate_assert "_SHMATE_JOB_RUN_DIR must be empty, but is \"${_SHMATE_JOB_RUN_DIR}\"" || return $?

    shmate_log_info "Hello, I'm an attached job and I don't know my name"

    return 0
}

_test_attached_job "$@"
