#!/usr/bin/env bash

. "${SHMATE_LIB_DIR}/assert.sh"

_test_detached_job() {
    local shmate_env=
    shmate_env=$(env | shmate_filter_grep -E '^_+SHMATE_' | sort)
    shmate_assert 'Reading shMate internal environment' || return $?

    test -z "${shmate_env}"
    shmate_assert "shMate internal environment variables must be unset, but are:
${shmate_env}" || return $?

    shmate_log_info "Hello, I'm a detached job and I don't know my name"

    return 0
}

_test_detached_job "$@"
