name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
